export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS ';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS ';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS ';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS ';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const START_TIME_TRACKER = 'START_TIME_TRACKER ';
export const STOP_TIME_TRACKER = 'STOP_TIME_TRACKER ';
export const RESTART_TASK = 'RESTART_TASK ';
export const STOP_TASK = 'STOP_TASK ';
export const RENAME_TASK = 'RENAME_TASK ';
export const DELETE_TASK = 'DELETE_TASK ';
export const SELECT_TASK = 'SELECT_TASK ';


